version: '2'

services:
  db:
    image: postgres
  cache:
    image: redis
  web:
    build: .
#    command: bash -c './wait-for-it db:5432 -- python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000'
    command: bash -c './run-server.sh'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
